apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boost-dev-hellowhale-deployment
  namespace: dev
  labels:
    app: boost-dev-hellowhale
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: boost-dev-hellowhale
  template:
    metadata:
      labels:
        app: boost-dev-hellowhale
    spec:
      containers:
      - name: boost-dev-hellowhale
        image: karimunjawa.boost.id/axiata/boost-dev-hellowhale:latest
        imagePullPolicy: Always
        ports:
        - name: backend-http
          containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: boost-dev-hellowhale-service
  namespace: dev
  labels:
    app: boost-dev-hellowhale
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:986794076402:certificate/064e7696-9b42-4831-8f68-72b43b8a2941
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: backend-http
  - port: 443
    name: https
    targetPort: backend-http
  selector:
    app: boost-dev-hellowhale
